version: 2.1 
jobs: 
  build-and-test:  
    machine: 
      image: ubuntu-2004:current 
    steps: 
      - checkout 
      - run:
            name: Install requirements
            command: make deps
      - run: 
            name: Inter on
            command: make lint
      - run: 
            name: test
            command: make test
workflows: 
  basic:  
    jobs: 
      - build-and-test 