version: 2.1 
jobs: 
  build-and-test:  
    machine: 
      image: ubuntu-2004:current
      docker_layer_caching: true
    steps: 
      - checkout 
      - run:
            name: Install requirements
            command: make deps
      - run: 
            name: Inter on
            command: make lint
      - run: 
            name: test
            command: make test
      - run:
            name: Docker
            command: make docker_build
      - run:
            name: Docker_Hub
            command: make docker_push
workflows: 
  basic:  
    jobs: 
      - build-and-test 